---
title: "Second Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: kable
    toc: true
---

```{r libraries, echo=FALSE, message=FALSE}
library(tidyverse)
library(janitor)
library(ggridges)
library(leaflet)
library(plotly)
library(rvent)
library(htmlwidgets)
```

```{r get_data, echo=FALSE}
# c_dat <- read.csv("/Users/heverz/Documents/R_projects/rden/static/data/data_crashes/Maryland_Statewide_Vehicle_Crashes.csv", na.strings=c(""," ","NA")) %>%
#   janitor::clean_names()
c_dat <- readRDS("c_dat.RDS")

# remove "SPUR FR " and SPUR TO " from mainroad_name and reference_road_name
c_dat <- c_dat %>%
  mutate_at(c("mainroad_name", "reference_road_name"), ~ str_remove(., "(SPUR FR )|(SPUR TO )"))
```

We filter for all crashes in Howard county in which either the `MAINROAD_NAME` or `REFERENCE_ROAD_NAME` are `COLUMBIA PIKE`.

```{r county, echo=FALSE}
howard_39 <- c_dat %>%
  filter(county_desc == "Howard") %>% 
  filter(mainroad_name == "COLUMBIA PIKE" | reference_road_name == "COLUMBIA PIKE")

# summary(howard_39)
```

```{r map, echo=FALSE}
howard_39 %>%
  select(latitude, longitude) %>%

  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(radius = 2,
      clusterOptions = "yes"
    )

```


```{r average_howard_bar, echo=FALSE}
howard_39 %>%
  unite("inters", c("mainroad_name", "reference_road_name"), sep = " + ") %>%
  group_by(inters, year) %>%
  summarize(n_cr = n()) %>%
  filter(!str_detect(inters, "\\+\\sNA$")) %>% 
  group_by(year) %>% 
  summarize(mean = mean(n_cr), sd = sd(n_cr), median = median(n_cr), n = n(), err = sd/sqrt(n)) %>% 
  
  ggplot(aes(x = year, y = mean)) + 
    geom_col(fill = "grey", col = "black") +
    scale_y_continuous(breaks = 1:18, minor_breaks = NULL, limits = c(0,18)) +
    geom_linerange(aes(ymin = mean, ymax = mean + sd), linetype = 1) +
    labs(y = "number of crashes (+/- st.dev)", 
         title = "Average Crashes per Intersection in Howard County") +
    geom_label(aes(year, 1, label = round(mean, digit = 2))) +
    theme_bw()
```
```{r iplot}
iplot <- howard_39 %>%
  unite("inters", c("mainroad_name", "reference_road_name"), sep = " + ") %>%
  group_by(inters, year) %>%
  summarize(n_cr = n()) %>%
  filter(!str_detect(inters, "\\+\\sNA$")) %>%
  filter(inters != "COLUMBIA PIKE + NO NAME") %>%{
    .[, "facet"] <- recode_col(.$inters, c(rep(1:10, 10), 1, 2))
    .
  } %>% 
  ungroup() %>% 
  ggplot(aes(x = year, y = n_cr, colour = inters, alpha = 0.5)) + 
    geom_point(position = position_dodge(0.4)) +
    geom_line(aes(group = inters), position = position_dodge(0.4)) +
    # geom_line(aes(group = inter)) +
    scale_y_continuous(breaks = seq(0,20, 2), minor_breaks = NULL, limits = c(0,20)) +
    # geom_linerange(aes(ymin = mean, ymax = mean + sd), linetype = 1) +
    labs(y = "number of crashes", 
         title = "Howard County, intersections of Columbia Pike") +
    theme_bw() +
    facet_wrap(~facet, nrow = 2) +
    theme(legend.position = "none",
          strip.background = element_blank(),
          strip.text.x = element_blank()) 
iplot <- ggplotly(iplot, width = 1000, height = 500)

saveWidget(iplot, "howard_intersections.html")

```

```{r}
howard_39 %>%
  unite("inters", c("mainroad_name", "reference_road_name"), sep = " + ") %>%
  filter(!str_detect(inters, "\\+\\sNA$")) %>%
  filter(inters == "COLUMBIA PIKE + NO NAME") %>% 
    select(latitude, longitude) %>%

  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(radius = 2,
      clusterOptions = "yes"
    )
```

```{r}
howard_39 %>% 
  pivot_longer(year)
```

